"""
fix_menu_ux.py
Modifies create_html.py to make the dropdown menu look and behave like
a proper dropdown (with backdrop, close button, Escape key support)
instead of a sidebar.
"""

import sys
import base64

FILE = r"C:\Users\AB Digial\OneDrive\Documents\Claude\create_html.py"

# Replacement blocks stored as base64 to avoid quoting issues
OLD_CSS_B64 = "ICAubWVudS1wYW5lbCB7ewogICAgcG9zaXRpb246IGZpeGVkOwogICAgdG9wOiA0MnB4OwogICAgbGVmdDogMTJweDsKICAgIG1pbi13aWR0aDogMjYwcHg7CiAgICBtYXgtd2lkdGg6IDMwMHB4OwogICAgbWF4LWhlaWdodDogNzV2aDsKICAgIG92ZXJmbG93LXk6IGF1dG87CiAgICBiYWNrZ3JvdW5kOiByZ2JhKDI1NSwyNTUsMjU1LDAuOTcpOwogICAgYmFja2Ryb3AtZmlsdGVyOiBibHVyKDE2cHgpOwogICAgLXdlYmtpdC1iYWNrZHJvcC1maWx0ZXI6IGJsdXIoMTZweCk7CiAgICBib3JkZXItcmFkaXVzOiAxMHB4OwogICAgYm94LXNoYWRvdzogMCA4cHggMzJweCByZ2JhKDAsMCwwLDAuMTIpLCAwIDJweCA4cHggcmdiYSgwLDAsMCwwLjA2KTsKICAgIHotaW5kZXg6IDk5OTk7CiAgICBib3JkZXI6IDFweCBzb2xpZCByZ2JhKDAsMCwwLDAuMDgpOwogICAgcGFkZGluZzogNHB4IDA7CiAgICBhbmltYXRpb246IG1lbnVGYWRlSW4gMC4xNXMgZWFzZS1vdXQ7CiAgfX0KICBAa2V5ZnJhbWVzIG1lbnVGYWRlSW4ge3sKICAgIGZyb20ge3sgb3BhY2l0eTogMDsgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC04cHgpOyB9fQogICAgdG8ge3sgb3BhY2l0eTogMTsgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKDApOyB9fQogIH19CiAgLm1lbnUtcGFuZWwtaGVhZGVyIHt7CiAgICBwYWRkaW5nOiAxMHB4IDE2cHggOHB4IDE2cHg7CiAgICBmb250LWZhbWlseTogJ0ZyYXVuY2VzJywgc2VyaWY7CiAgICBmb250LXNpemU6IDAuOWVtOwogICAgZm9udC13ZWlnaHQ6IDcwMDsKICAgIGNvbG9yOiB2YXIoLS1mb3Jlc3QpOwogICAgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgICBtYXJnaW4tYm90dG9tOiA0cHg7CiAgfX0KICAubWVudS1wYW5lbCBhIHt7CiAgICBkaXNwbGF5OiBibG9jazsKICAgIHBhZGRpbmc6IDhweCAxNnB4OwogICAgZm9udC1mYW1pbHk6ICdPdXRmaXQnLCBzYW5zLXNlcmlmOwogICAgZm9udC1zaXplOiAwLjgyZW07CiAgICBjb2xvcjogdmFyKC0tdGV4dCk7CiAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICB0cmFuc2l0aW9uOiBiYWNrZ3JvdW5kIDAuMTVzOwogICAgYm9yZGVyLXJhZGl1czogMDsKICAgIGJvcmRlcjogbm9uZTsKICAgIG1hcmdpbjogMDsKICAgIGJhY2tncm91bmQ6IHRyYW5zcGFyZW50OwogIH19CiAgLm1lbnUtcGFuZWwgYTpob3ZlciB7ewogICAgYmFja2dyb3VuZDogI2YwZmRmNDsKICAgIGNvbG9yOiB2YXIoLS1mb3Jlc3QpOwogICAgdHJhbnNmb3JtOiBub25lOwogICAgYm94LXNoYWRvdzogbm9uZTsKICB9fQ=="
NEW_CSS_B64 = "ICAubWVudS1iYWNrZHJvcCB7ewogICAgcG9zaXRpb246IGZpeGVkOwogICAgaW5zZXQ6IDA7CiAgICBiYWNrZ3JvdW5kOiByZ2JhKDAsMCwwLDAuMjUpOwogICAgei1pbmRleDogOTk5ODsKICAgIGFuaW1hdGlvbjogYmFja2Ryb3BJbiAwLjE1cyBlYXNlLW91dDsKICB9fQogIEBrZXlmcmFtZXMgYmFja2Ryb3BJbiB7ewogICAgZnJvbSB7eyBvcGFjaXR5OiAwOyB9fQogICAgdG8ge3sgb3BhY2l0eTogMTsgfX0KICB9fQogIC5tZW51LXBhbmVsIHt7CiAgICBwb3NpdGlvbjogZml4ZWQ7CiAgICB0b3A6IDQwcHg7CiAgICBsZWZ0OiAxMHB4OwogICAgd2lkdGg6IDI2MHB4OwogICAgbWF4LWhlaWdodDogODB2aDsKICAgIG92ZXJmbG93LXk6IGF1dG87CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1jcmVhbSk7CiAgICBib3JkZXItcmFkaXVzOiAxMnB4OwogICAgYm94LXNoYWRvdzogMCAyMHB4IDYwcHggcmdiYSgwLDAsMCwwLjIpLCAwIDRweCAxNnB4IHJnYmEoMCwwLDAsMC4xKTsKICAgIHotaW5kZXg6IDk5OTk7CiAgICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgcGFkZGluZzogMDsKICAgIGFuaW1hdGlvbjogbWVudUZhZGVJbiAwLjJzIGN1YmljLWJlemllciguNCwwLC4yLDEpOwogIH19CiAgQGtleWZyYW1lcyBtZW51RmFkZUluIHt7CiAgICBmcm9tIHt7IG9wYWNpdHk6IDA7IHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtNnB4KSBzY2FsZSgwLjk3KTsgfX0KICAgIHRvIHt7IG9wYWNpdHk6IDE7IHRyYW5zZm9ybTogdHJhbnNsYXRlWSgwKSBzY2FsZSgxKTsgfX0KICB9fQogIC5tZW51LXBhbmVsLWhlYWRlciB7ewogICAgZGlzcGxheTogZmxleDsKICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47CiAgICBwYWRkaW5nOiAxMnB4IDE0cHggMTBweDsKICAgIGZvbnQtZmFtaWx5OiAnRnJhdW5jZXMnLCBzZXJpZjsKICAgIGZvbnQtc2l6ZTogMC44NWVtOwogICAgZm9udC13ZWlnaHQ6IDcwMDsKICAgIGNvbG9yOiB2YXIoLS1mb3Jlc3QpOwogICAgYm9yZGVyLWJvdHRvbTogMS41cHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIGJhY2tncm91bmQ6IHJnYmEoMjcsNjcsNTAsMC4wNCk7CiAgfX0KICAubWVudS1jbG9zZSB7ewogICAgYmFja2dyb3VuZDogbm9uZTsKICAgIGJvcmRlcjogbm9uZTsKICAgIGZvbnQtc2l6ZTogMS4xZW07CiAgICBjb2xvcjogdmFyKC0tZm9yZXN0KTsKICAgIGN1cnNvcjogcG9pbnRlcjsKICAgIHBhZGRpbmc6IDJweCA2cHg7CiAgICBib3JkZXItcmFkaXVzOiA0cHg7CiAgICBsaW5lLWhlaWdodDogMTsKICAgIHRyYW5zaXRpb246IGJhY2tncm91bmQgMC4xNXM7CiAgfX0KICAubWVudS1jbG9zZTpob3ZlciB7ewogICAgYmFja2dyb3VuZDogcmdiYSgyNyw2Nyw1MCwwLjEpOwogIH19CiAgLm1lbnUtcGFuZWwgYSB7ewogICAgZGlzcGxheTogZmxleDsKICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICBnYXA6IDZweDsKICAgIHBhZGRpbmc6IDlweCAxNHB4OwogICAgZm9udC1mYW1pbHk6ICdPdXRmaXQnLCBzYW5zLXNlcmlmOwogICAgZm9udC1zaXplOiAwLjhlbTsKICAgIGNvbG9yOiB2YXIoLS10ZXh0KTsKICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTsKICAgIHRyYW5zaXRpb246IGJhY2tncm91bmQgMC4xMnM7CiAgICBib3JkZXItcmFkaXVzOiAwOwogICAgYm9yZGVyOiBub25lOwogICAgbWFyZ2luOiAwOwogICAgYmFja2dyb3VuZDogdHJhbnNwYXJlbnQ7CiAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgcmdiYSgwLDAsMCwwLjA0KTsKICB9fQogIC5tZW51LXBhbmVsIGE6bGFzdC1jaGlsZCB7ewogICAgYm9yZGVyLWJvdHRvbTogbm9uZTsKICB9fQogIC5tZW51LXBhbmVsIGE6aG92ZXIge3sKICAgIGJhY2tncm91bmQ6IHJnYmEoMjcsNjcsNTAsMC4wNik7CiAgICBjb2xvcjogdmFyKC0tZm9yZXN0KTsKICAgIHRyYW5zZm9ybTogbm9uZTsKICAgIGJveC1zaGFkb3c6IG5vbmU7CiAgfX0="
OLD_JS_B64 = "ICAvLyBCb2R5LWFwcGVuZGVkIGRyb3Bkb3duIG1lbnUKICAoZnVuY3Rpb24oKSB7e3t7CiAgICB2YXIgbWVudUJ0biA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJtYWluTWVudUJ0biIpOwogICAgaWYgKCFtZW51QnRuKSByZXR1cm47CgogICAgdmFyIG1lbnVJdGVtcyA9IFsKICAgICAge3tocmVmOiAiI3JlZi0wIiwgbGFiZWw6ICLwn5SAIEZsZXhpYmlsaXR5IEd1aWRlIn19LAogICAgICB7e2hyZWY6ICIjcmVmLTEiLCBsYWJlbDogIvCfk4UgRXZlbnRzIENhbGVuZGFyIn19LAogICAgICB7e2hyZWY6ICIjcmVmLTIiLCBsYWJlbDogIvCfk4sgQm9va2luZyBDaGVja2xpc3QifX0sCiAgICAgIHt7aHJlZjogIiNyZWYtMyIsIGxhYmVsOiAi8J+apyBSb2FkIENvbmRpdGlvbnMifX0sCiAgICAgIHt7aHJlZjogIiNyZWYtNCIsIGxhYmVsOiAi8J+Xuu+4jyBEcml2aW5nIFN1bW1hcnkifX0sCiAgICAgIHt7aHJlZjogIiNyZWYtNSIsIGxhYmVsOiAi8J+PoCBMb2RnaW5nIEd1aWRlIn19LAogICAgICB7e2hyZWY6ICIjcmVmLTYiLCBsYWJlbDogIvCfj5TvuI8gTGFuZCBTY291dGluZyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi03IiwgbGFiZWw6ICLwn5ONIFNjb3V0aW5nIFN1bW1hcnkifX0sCiAgICAgIHt7aHJlZjogIiNyZWYtOCIsIGxhYmVsOiAi8J+TjSBDb250ZXh0In19LAogICAgICB7e2hyZWY6ICIjcmVmLTkiLCBsYWJlbDogIvCfm5IgQ29zdGNvIExvY2F0aW9ucyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0xMCIsIGxhYmVsOiAi8J+alyBWZWhpY2xlIE5vdGVzIn19LAogICAgICB7e2hyZWY6ICIjcmVmLTExIiwgbGFiZWw6ICLwn6aHIEhvcnJvciAmIFNwb29reSBTaG9wcyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0xMiIsIGxhYmVsOiAi8J+OriBLaWQtRnJpZW5kbHkgQWN0aXZpdGllcyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0xMyIsIGxhYmVsOiAi8J+nsyBQYWNraW5nIExpc3QifX0KICAgIF07CgogICAgZnVuY3Rpb24gY2xvc2VNZW51KCkge3t7ewogICAgICB2YXIgZXhpc3RpbmcgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIubWVudS1wYW5lbCIpOwogICAgICBpZiAoZXhpc3RpbmcpIGV4aXN0aW5nLnJlbW92ZSgpOwogICAgfX19fQoKICAgIG1lbnVCdG4uYWRkRXZlbnRMaXN0ZW5lcigiY2xpY2siLCBmdW5jdGlvbihlKSB7e3t7CiAgICAgIGUuc3RvcFByb3BhZ2F0aW9uKCk7CiAgICAgIHZhciBleGlzdGluZyA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIi5tZW51LXBhbmVsIik7CiAgICAgIGlmIChleGlzdGluZykge3t7ewogICAgICAgIGV4aXN0aW5nLnJlbW92ZSgpOwogICAgICAgIHJldHVybjsKICAgICAgfX19fQogICAgICB2YXIgcGFuZWwgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJkaXYiKTsKICAgICAgcGFuZWwuY2xhc3NOYW1lID0gIm1lbnUtcGFuZWwiOwogICAgICB2YXIgaGVhZGVyID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiZGl2Iik7CiAgICAgIGhlYWRlci5jbGFzc05hbWUgPSAibWVudS1wYW5lbC1oZWFkZXIiOwogICAgICBoZWFkZXIudGV4dENvbnRlbnQgPSAiUmVmZXJlbmNlICYgUGxhbm5pbmciOwogICAgICBwYW5lbC5hcHBlbmRDaGlsZChoZWFkZXIpOwogICAgICBtZW51SXRlbXMuZm9yRWFjaChmdW5jdGlvbihpdGVtKSB7e3t7CiAgICAgICAgdmFyIGEgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJhIik7CiAgICAgICAgYS5ocmVmID0gaXRlbS5ocmVmOwogICAgICAgIGEudGV4dENvbnRlbnQgPSBpdGVtLmxhYmVsOwogICAgICAgIGEuYWRkRXZlbnRMaXN0ZW5lcigiY2xpY2siLCBmdW5jdGlvbigpIHt7e3sKICAgICAgICAgIGNsb3NlTWVudSgpOwogICAgICAgIH19fX0pOwogICAgICAgIHBhbmVsLmFwcGVuZENoaWxkKGEpOwogICAgICB9fX19KTsKICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChwYW5lbCk7CiAgICB9fX19KTsKCiAgICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCJjbGljayIsIGZ1bmN0aW9uKGUpIHt7e3sKICAgICAgaWYgKCFlLnRhcmdldC5jbG9zZXN0KCIubWVudS1wYW5lbCIpICYmIGUudGFyZ2V0ICE9PSBtZW51QnRuKSB7e3t7CiAgICAgICAgY2xvc2VNZW51KCk7CiAgICAgIH19fX0KICAgIH19fX0pOwogIH19fX0pKCk7"
NEW_JS_B64 = "ICAvLyBCb2R5LWFwcGVuZGVkIGRyb3Bkb3duIG1lbnUgd2l0aCBiYWNrZHJvcAogIChmdW5jdGlvbigpIHt7e3sKICAgIHZhciBtZW51QnRuID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoIm1haW5NZW51QnRuIik7CiAgICBpZiAoIW1lbnVCdG4pIHJldHVybjsKCiAgICB2YXIgbWVudUl0ZW1zID0gWwogICAgICB7e2hyZWY6ICIjcmVmLTAiLCBsYWJlbDogIkZsZXhpYmlsaXR5IEd1aWRlIn19LAogICAgICB7e2hyZWY6ICIjcmVmLTEiLCBsYWJlbDogIkV2ZW50cyBDYWxlbmRhciJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0yIiwgbGFiZWw6ICJCb29raW5nIENoZWNrbGlzdCJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0zIiwgbGFiZWw6ICJSb2FkIENvbmRpdGlvbnMifX0sCiAgICAgIHt7aHJlZjogIiNyZWYtNCIsIGxhYmVsOiAiRHJpdmluZyBTdW1tYXJ5In19LAogICAgICB7e2hyZWY6ICIjcmVmLTUiLCBsYWJlbDogIkxvZGdpbmcgR3VpZGUifX0sCiAgICAgIHt7aHJlZjogIiNyZWYtNiIsIGxhYmVsOiAiTGFuZCBTY291dGluZyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi03IiwgbGFiZWw6ICJTY291dGluZyBTdW1tYXJ5In19LAogICAgICB7e2hyZWY6ICIjcmVmLTgiLCBsYWJlbDogIkNvbnRleHQifX0sCiAgICAgIHt7aHJlZjogIiNyZWYtOSIsIGxhYmVsOiAiQ29zdGNvIExvY2F0aW9ucyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0xMCIsIGxhYmVsOiAiVmVoaWNsZSBOb3RlcyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0xMSIsIGxhYmVsOiAiSG9ycm9yICYgU3Bvb2t5IFNob3BzIn19LAogICAgICB7e2hyZWY6ICIjcmVmLTEyIiwgbGFiZWw6ICJLaWQtRnJpZW5kbHkgQWN0aXZpdGllcyJ9fSwKICAgICAge3tocmVmOiAiI3JlZi0xMyIsIGxhYmVsOiAiUGFja2luZyBMaXN0In19CiAgICBdOwoKICAgIGZ1bmN0aW9uIGNsb3NlTWVudSgpIHt7e3sKICAgICAgdmFyIHBhbmVsID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiLm1lbnUtcGFuZWwiKTsKICAgICAgdmFyIGJhY2tkcm9wID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiLm1lbnUtYmFja2Ryb3AiKTsKICAgICAgaWYgKHBhbmVsKSBwYW5lbC5yZW1vdmUoKTsKICAgICAgaWYgKGJhY2tkcm9wKSBiYWNrZHJvcC5yZW1vdmUoKTsKICAgIH19fX0KCiAgICBtZW51QnRuLmFkZEV2ZW50TGlzdGVuZXIoImNsaWNrIiwgZnVuY3Rpb24oZSkge3t7ewogICAgICBlLnN0b3BQcm9wYWdhdGlvbigpOwogICAgICBpZiAoZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiLm1lbnUtcGFuZWwiKSkge3t7ewogICAgICAgIGNsb3NlTWVudSgpOwogICAgICAgIHJldHVybjsKICAgICAgfX19fQoKICAgICAgdmFyIGJhY2tkcm9wID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiZGl2Iik7CiAgICAgIGJhY2tkcm9wLmNsYXNzTmFtZSA9ICJtZW51LWJhY2tkcm9wIjsKICAgICAgYmFja2Ryb3AuYWRkRXZlbnRMaXN0ZW5lcigiY2xpY2siLCBjbG9zZU1lbnUpOwogICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGJhY2tkcm9wKTsKCiAgICAgIHZhciBwYW5lbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoImRpdiIpOwogICAgICBwYW5lbC5jbGFzc05hbWUgPSAibWVudS1wYW5lbCI7CgogICAgICB2YXIgaGVhZGVyID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiZGl2Iik7CiAgICAgIGhlYWRlci5jbGFzc05hbWUgPSAibWVudS1wYW5lbC1oZWFkZXIiOwogICAgICB2YXIgaGVhZGVyVGV4dCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoInNwYW4iKTsKICAgICAgaGVhZGVyVGV4dC50ZXh0Q29udGVudCA9ICJKdW1wIHRvIFNlY3Rpb24iOwogICAgICBoZWFkZXIuYXBwZW5kQ2hpbGQoaGVhZGVyVGV4dCk7CiAgICAgIHZhciBjbG9zZUJ0biA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoImJ1dHRvbiIpOwogICAgICBjbG9zZUJ0bi5jbGFzc05hbWUgPSAibWVudS1jbG9zZSI7CiAgICAgIGNsb3NlQnRuLmlubmVySFRNTCA9ICLinJUiOwogICAgICBjbG9zZUJ0bi5hZGRFdmVudExpc3RlbmVyKCJjbGljayIsIGNsb3NlTWVudSk7CiAgICAgIGhlYWRlci5hcHBlbmRDaGlsZChjbG9zZUJ0bik7CiAgICAgIHBhbmVsLmFwcGVuZENoaWxkKGhlYWRlcik7CgogICAgICBtZW51SXRlbXMuZm9yRWFjaChmdW5jdGlvbihpdGVtKSB7e3t7CiAgICAgICAgdmFyIGEgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJhIik7CiAgICAgICAgYS5ocmVmID0gaXRlbS5ocmVmOwogICAgICAgIGEudGV4dENvbnRlbnQgPSBpdGVtLmxhYmVsOwogICAgICAgIGEuYWRkRXZlbnRMaXN0ZW5lcigiY2xpY2siLCBmdW5jdGlvbigpIHt7e3sKICAgICAgICAgIGNsb3NlTWVudSgpOwogICAgICAgIH19fX0pOwogICAgICAgIHBhbmVsLmFwcGVuZENoaWxkKGEpOwogICAgICB9fX19KTsKCiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQocGFuZWwpOwogICAgfX19fSk7CgogICAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcigia2V5ZG93biIsIGZ1bmN0aW9uKGUpIHt7e3sKICAgICAgaWYgKGUua2V5ID09PSAiRXNjYXBlIikgY2xvc2VNZW51KCk7CiAgICB9fX19KTsKICB9fX19KSgpOw=="

OLD_CSS = base64.b64decode(OLD_CSS_B64).decode("utf-8")
NEW_CSS = base64.b64decode(NEW_CSS_B64).decode("utf-8")
OLD_JS = base64.b64decode(OLD_JS_B64).decode("utf-8")
NEW_JS = base64.b64decode(NEW_JS_B64).decode("utf-8")

with open(FILE, "r", encoding="utf-8") as f:
    content = f.read()

original_len = len(content)
errors = []

# Change 1 - CSS
if OLD_CSS in content:
    content = content.replace(OLD_CSS, NEW_CSS, 1)
    print("[OK] Change 1 (CSS): replacement applied.")
else:
    errors.append("Change 1 (CSS): OLD block NOT found in file.")
    print("[FAIL] " + errors[-1])

# Change 2 - JS
if OLD_JS in content:
    content = content.replace(OLD_JS, NEW_JS, 1)
    print("[OK] Change 2 (JS):  replacement applied.")
else:
    errors.append("Change 2 (JS): OLD block NOT found in file.")
    print("[FAIL] " + errors[-1])

if errors:
    print(f"\n{len(errors)} replacement(s) FAILED. File was NOT written.")
    sys.exit(1)

# Verify the new blocks are present
checks = [
    (".menu-backdrop CSS", ".menu-backdrop {{" in content),
    ("@keyframes backdropIn", "@keyframes backdropIn" in content),
    (".menu-close CSS", ".menu-close {{" in content),
    ("menu-panel a:last-child", ".menu-panel a:last-child" in content),
    ("backdrop JS creation", "backdrop.className" in content),
    ("closeBtn JS", "closeBtn.className" in content),
    ("Escape key handler", "Escape" in content),
    ("Jump to Section header", "Jump to Section" in content),
    ("Emoji-free labels", 'label: "Flexibility Guide"' in content),
]

all_ok = True
for name, ok in checks:
    status = "PASS" if ok else "FAIL"
    if not ok:
        all_ok = False
    print(f"  verify {name}: [{status}]")

if not all_ok:
    print("\nSome verifications failed. File was NOT written.")
    sys.exit(1)

with open(FILE, "w", encoding="utf-8") as f:
    f.write(content)

print(f"\nFile written successfully.")
print(f"  Original size: {original_len:,} chars")
print(f"  New size:      {len(content):,} chars")
print(f"  Delta:         {len(content) - original_len:+,} chars")
print("\nAll changes applied and verified.")
